Updated CLOC to 0.6.1 version. Two new paths need to be set. HSA_LLVM_PATH (Path to HSAIL_LLVM_BACKEND/bin) and HSA_LIBHSAIL_PATH (Path to HSAIL-Tools/libHSAIL/build_linux). There are also makefile changes in the examples. Make all and make tests build and execute the tests.
Former-commit-id: f4d9e02f85340a8543525d22c005950571d3c2d2

diff --git a/cloc b/cloc
--- a/cloc
+++ b/cloc
@@ -19,7 +19,7 @@ function usage(){
 
    Options without values:
     -hsail  Generate hsail instead of brig 
-    -c      Compile hsail or brig to .o object file 
+    -str    Saves the output as a string in a header file and compiles it to .o object file 
     -v      Display version of cloc then exit
     -q      Run quietly, no messages 
     -n      Dryrun, do nothing, show commands that would execute
@@ -32,18 +32,19 @@ function usage(){
     -lkopts <linker options> LKOPTS, Read cloc script for defaults
     -s      <symbolname> , Default=filename (only with -c)
     -t      <tdir> Temporary directory, Default=/tmp/cloc$$
-    -p      <path> HSBEPATH, Default=$HSBEPATH or /usr/local/HSAIL_LLVM_Backend/bin
+    -p1      <path> HSA_LLVM_PATH, Default=$HSA_LLVM_PATH or /usr/local/HSAIL_LLVM_Backend/bin
+    -p2      <path> HSA_LIBHSAIL_PATH, Default=$HSA_LIBHSAIL_PATH or /usr/local/HSAIL-Tools/libHSAIL/build_linux
     -o      <outfilename>, Default=<filename>.<ft> where ft is brig, hsail, or o
 
    Examples:
       cloc mykernel.cl              /* creates mykernel.brig  */
-      cloc -c mykernel.cl           /* creates mykernel.o     */
+      cloc -str mykernel.cl           /* creates mykernel.o     */
       cloc -hsail mykernel.cl       /* creates mykernel.hsail */
-      cloc -c -hsail mykernel.cl    /* creates mykernel.o     */
+      cloc -str -hsail mykernel.cl    /* creates mykernel.o     */
       cloc -t /tmp/foo mykernel.cl  /* automatically sets -k  */
-      cloc -c -nq -clopts "--opencl=2.0" mykernel.cl
+      cloc -str -nq -clopts "--opencl=2.0" mykernel.cl
 
-   You may set environment variables HSBEPATH, CLOPTS, or LKOPTS instead 
+   You may set environment variables HSA_LLVM_PATH, HSA_LIBHSAIL_PATH, CLOPTS, or LKOPTS instead 
    of using the command line options -p, -clopts, or -lkopts.  
    Command line options take precedence over the environment variables. 
 
@@ -94,14 +95,15 @@ while [ $# -gt 0 ] ; do
       -n) 		DRYRUN=true;; 
       -nq) 		DRYRUN=true;QUIET=true;;
       -qn) 		DRYRUN=true;QUIET=true;; 
-      -c) 		MAKEOBJ=true;; 
+      -str) 		MAKEOBJ=true;; 
       -hsail) 		HSAIL=true;; 
       -clopts) 		CLOPTS=$2; shift ;; 
       -lkopts) 		LKOPTS=$2; shift ;; 
       -s) 		SYMBOLNAME=$2; shift ;; 
       -o) 		OUTFILE=$2; shift ;; 
       -t) 		TMPDIR=$2; shift ;; 
-      -p) 		HSBEPATH=$2; shift ;; 
+      -p1) 		HSA_LLVM_PATH=$2; shift ;; 
+      -p2) 		HSA_LIBHSAIL_PATH=$2; shift ;; 
       -h) 		usage ;; 
       -help) 		usage ;; 
       --help) 		usage ;; 
@@ -121,11 +123,13 @@ shift
 if ! [ $QUIET ] ; then  VERBOSE=true ; fi
 
 #  Set Default values
-HSBEPATH=${HSBEPATH:-/usr/local/HSAIL_LLVM_Backend/bin}
+HSA_LLVM_PATH=${HSA_LLVM_PATH:-/usr/local/HSAIL_LLVM_Backend}
+HSA_LIBHSAIL_PATH=${HSA_LIBHSAIL_PATH:-/usr/local/HSAIL-tools/libHSAIL/build}
+
 #CLOPTS=${CLOPTS:---opencl=1.2}
 CMD_CLC=${CMD_CLC:-clc2 -cl-std=CL2.0 $CLOPTS}
 CMD_LLA=${CMD_LLA:-llvm-dis}
-LKOPTS=${LKOPTS:--prelink-opt -l $HSBEPATH/builtins-hsail.bc -l $HSBEPATH/builtins-hsail-amd-ci.bc -l $HSBEPATH/builtins-gcn.bc}
+LKOPTS=${LKOPTS:--prelink-opt -l $HSA_LLVM_PATH/builtins-hsail.bc -l $HSA_LLVM_PATH/builtins-hsail-amd-ci.bc -l $HSA_LLVM_PATH/builtins-gcn.bc}
 CMD_LLL=${CMD_LLL:-llvm-link $LKOPTS}
 CMD_OPT=${CMD_OPT:-opt -O3 -gpu -whole}
 CMD_LLC=${CMD_LLC:-llc -O2 -march=hsail-64}
@@ -187,12 +191,17 @@ if [ ! -d $TMPDIR ] && [ ! $DRYRUN ] ; then
    echo "ERROR:  Directory $TMPDIR does not exist or could not be created"
    exit $DEADRC
 fi 
-if [ ! -d $HSBEPATH ] ; then 
-   echo "ERROR:  HSBEPATH $HSBEPATH does not exist. Consider -p option"
+if [ ! -d $HSA_LLVM_PATH ] ; then 
+   echo "ERROR:  HSA_LLVM_PATH $HSA_LLVM_PATH does not exist. Consider -p option"
    exit $DEADRC
 fi 
-if [ ! -e $HSBEPATH/hsailasm ] ; then 
-   echo "ERROR:  HSBEPATH $HSBEPATH does not contain HSAILasm. "
+if [ ! -d $HSA_LIBHSAIL_PATH ] ; then 
+   echo "ERROR:  HSA_LIBHSAIL_PATH $HSA_LIBHSAIL_PATH does not exist. Consider -p option"
+   exit $DEADRC
+fi 
+
+if [ ! -e $HSA_LIBHSAIL_PATH/hsailasm ] ; then 
+   echo "ERROR:  HSA_LIBHSAIL_PATH $HSA_LIBHSAIL_PATH does not contain hsailasm. "
    echo "        This directory does not have HSAIL backend. Consider -p option"
    exit $DEADRC
 fi 
@@ -208,9 +217,9 @@ if [ $MAKEOBJ ] ; then
    fi
 fi
 
-PATH=$HSBEPATH:$PATH
+PATH=$HSA_LLVM_PATH:$HSA_LIBHSAIL_PATH:$PATH
 if [ $DRYRUN ] ; then 
-   echo "export PATH=$HSBEPATH:\$PATH"
+   echo "export PATH=$HSA_LLVM_PATH:$HSA_LIBHSAIL_PATH:$PATH"
 fi
 
 [ $VERBOSE ] && echo "#Info:  Version:	$PROGVERSION" 
@@ -225,7 +234,7 @@ rc=0
 if [ $DRYRUN ] ; then
    echo $CMD_CLC -o $TMPDIR/$FNAME.ll $INDIR/$CLNAME
 else
-   $HSBEPATH/$CMD_CLC -o $TMPDIR/$FNAME.bc $INDIR/$CLNAME
+   $HSA_LLVM_PATH/$CMD_CLC -o $TMPDIR/$FNAME.bc $INDIR/$CLNAME
    rc=$?
 fi
 if [ $rc != 0 ] ; then 
@@ -234,11 +243,11 @@ if [ $rc != 0 ] ; then
    do_err $rc
 fi
 
-[ $VERBOSE ] && echo "#Info:  Disassmbl(llvm-as)	bc --> ll ..."
+[ $VERBOSE ] && echo "#Info:  Disassmble(llvm-as)	bc --> ll ..."
 if [ $DRYRUN ] ; then
    echo $CMD_LLA -o $TMPDIR/$FNAME.ll $TMPDIR/$FNAME.bc
 else 
-   $HSBEPATH/$CMD_LLA -o $TMPDIR/$FNAME.ll $TMPDIR/$FNAME.bc
+   $HSA_LLVM_PATH/$CMD_LLA -o $TMPDIR/$FNAME.ll $TMPDIR/$FNAME.bc
    rc=$?
 fi
 if [ $rc != 0 ] ; then 
@@ -252,7 +261,7 @@ if [ $DRYRUN ] ; then
    echo $CMD_LLL -o $TMPDIR/$FNAME.lnkd.bc $TMPDIR/$FNAME.bc  
 else
 #  Hide the warnings for now
-   $HSBEPATH/$CMD_LLL -o $TMPDIR/$FNAME.lnkd.bc $TMPDIR/$FNAME.bc 2>/dev/null
+   $HSA_LLVM_PATH/$CMD_LLL -o $TMPDIR/$FNAME.lnkd.bc $TMPDIR/$FNAME.bc 2>/dev/null
    rc=$?
 fi
 if [ $rc != 0 ] ; then 
@@ -265,7 +274,7 @@ fi
 if [ $DRYRUN ] ; then
    echo $CMD_OPT -o $TMPDIR/$FNAME.opt.bc $TMPDIR/$FNAME.lnkd.bc
 else
-   $HSBEPATH/$CMD_OPT -o $TMPDIR/$FNAME.opt.bc $TMPDIR/$FNAME.lnkd.bc
+   $HSA_LLVM_PATH/$CMD_OPT -o $TMPDIR/$FNAME.opt.bc $TMPDIR/$FNAME.lnkd.bc
    rc=$?
 fi
 if [ $rc != 0 ] ; then 
@@ -305,7 +314,7 @@ fi
 if [ $DRYRUN ] ; then
    echo $CMD_LLC -o $BRIGDIR/$BRIGNAME $TMPDIR/$FNAME.opt.bc
 else
-   $HSBEPATH/$CMD_LLC -o $BRIGDIR/$BRIGNAME $TMPDIR/$FNAME.opt.bc
+   $HSA_LLVM_PATH/$CMD_LLC -o $BRIGDIR/$BRIGNAME $TMPDIR/$FNAME.opt.bc
    rc=$?
 fi
 if [ $rc != 0 ] ; then 
@@ -324,7 +333,7 @@ if [ $HSAIL ] ; then
    if [ $DRYRUN ] ; then
       echo $CMD_ASM -o $HSAILDIR/$HSAILNAME $TMPDIR/$FNAME.brig
    else
-      $HSBEPATH/$CMD_ASM -o $HSAILDIR/$HSAILNAME $TMPDIR/$FNAME.brig
+      $HSA_LLVM_PATH/$CMD_ASM -o $HSAILDIR/$HSAILNAME $TMPDIR/$FNAME.brig
       rc=$?
    fi
    if [ $rc != 0 ] ; then 
@@ -346,19 +355,19 @@ if [ $MAKEOBJ ] ; then
          echo "char ${SYMBOLNAME}[] = MULTILINE(" >> $TMPDIR/$FNAME.cpp
          cat $TMPDIR/$HSAILNAME >> $TMPDIR/$FNAME.cpp
          echo ");" >> $TMPDIR/$FNAME.cpp
-         $CMD_GCC -o $OUTDIR/$OUTFILE -c $TMPDIR/$FNAME.cpp
+         $CMD_GCC -o $OUTDIR/$OUTFILE -str $TMPDIR/$FNAME.cpp
          rc=$?
       fi
       if [ $rc != 0 ] ; then 
          echo "ERROR:  The following command failed with return code $rc."
-         echo "        $CMD_GCC -o $OUTDIR/$OUTFILE.o -c $TMPDIR/$FNAME.cpp"
+         echo "        $CMD_GCC -o $OUTDIR/$OUTFILE.o -str $TMPDIR/$FNAME.cpp"
          do_err $rc
       fi
    else
       [ $VERBOSE ] && echo "#Info:  gcc  	 	brig --> $OUTFILE ..."
       if [ $DRYRUN ] ; then
 #        Sorry, dont show the magic to create cpp
-         echo $CMD_GCC -o $OUTDIR/$OUTFILE -c $TMPDIR/$FNAME.cpp
+         echo $CMD_GCC -o $OUTDIR/$OUTFILE -str $TMPDIR/$FNAME.cpp
       else
          echo "#include <cstring>" > $TMPDIR/$FNAME.cpp
          echo "char ${SYMBOLNAME}[] = {" >> $TMPDIR/$FNAME.cpp
@@ -371,12 +380,12 @@ if [ $MAKEOBJ ] ; then
          echo "};" >> $TMPDIR/$FNAME.cpp
 #        okra needs the size of brig for createKernelFromBinary()
          echo "size_t ${SYMBOLNAME}sz = sizeof($SYMBOLNAME);" >> $TMPDIR/$FNAME.cpp
-         $CMD_GCC -o $OUTDIR/$OUTFILE -c $TMPDIR/$FNAME.cpp
+         $CMD_GCC -o $OUTDIR/$OUTFILE -str $TMPDIR/$FNAME.cpp
          rc=$?
       fi
       if [ $rc != 0 ] ; then 
          echo "ERROR:  The following command failed with return code $rc."
-         echo "        $CMD_GCC -o $OUTDIR/$OUTFILE -c $TMPDIR/$FNAME.cpp"
+         echo "        $CMD_GCC -o $OUTDIR/$OUTFILE -str $TMPDIR/$FNAME.cpp"
          do_err $rc
       fi
    fi
